### ISSUE TITLE
repodata being written to too many places during repo creation?

### ISSUE THREAD

**Issue by minddrive** [arnehilmann/yumrepos#7]
Setup: Docker container running CentOS 7.4, running latest commit of yumrepos via command line (developer mode)

Trying to set up new repositories, so in my Python code I have something like this:

`requests.put('http://localhost:8080/admin/v1/repos/enterprise/rpm/6/x86_64)`

which succeeds, but when I look at the newly created setup, I'm seeing duplication of the 'repodata' directory at multiple levels:

```
(yum-upload-test) [couchbase@92d92510e571 repo_upload]$ find ~/linux_repos/ -name repodata
/home/couchbase/linux_repos/couchbase-server/.metadata/__empty__/repodata
/home/couchbase/linux_repos/couchbase-server/enterprise/rpm/6/repodata
/home/couchbase/linux_repos/couchbase-server/enterprise/rpm/6/x86_64/repodata
/home/couchbase/linux_repos/couchbase-server/enterprise/rpm/repodata
/home/couchbase/linux_repos/couchbase-server/enterprise/repodata
```

(The yumrepos server was started with a base of '/home/couchbase/linux_repos/couchbase-server' instead of '/tmp/repos'.)  This doesn't seem quite right, I expected repodata only to be at the deepest level; is there something going on here I'm missing?

**Comment by arnehilmann** [comment]
Works as intended: you can use any directory under the repos base as repository.
It is up to you how to layout your repos: per distribution, per functionality, per organizational unit, ...
So every directory gets a repodata subdir, with repo metadata (probably empty, but present nevertheless to make yum happy)

**Comment by minddrive** [comment]
Unfortunately, this makes the program completely unusable for my purposes.  I wish you the best of luck, but I will be looking elsewhere.

**Comment by arnehilmann** [comment]
Out of curiosity: could you describe your usecase a bit, please?! Especially the ‘completely unusable’ part...
